version: "3.8"

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
    ports:
      - "3306:3306"

  backend:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mysql
